# [Choice] Debian / Ubuntu version: debian-10, debian-9, ubuntu-20.04, ubuntu-18.04
FROM mcr.jz.com/vscode/jzcontainers/arm64v8/rust:dev

# RUN rustup component add rustfmt
# [Optional] Uncomment this section to install additional OS packages you may want.
#
# RUN apk add --no-cache <your-package-list-here>
